import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { collection, getFirestore, onSnapshot, query, updateDoc, doc, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyD5tdmon0-6R_IABZyUo8QEfSKlTBrmLTo",authDomain:"markethub-prototype.firebaseapp.com",projectId:"markethub-prototype",storageBucket:"markethub-prototype.firebasestorage.app",messagingSenderId:"350124318634",appId:"1:350124318634:web:cb4401e9f84edcdd5995d3"};
const app=getApps().length?getApp():initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app);
const bell=document.getElementById("notification-bell"), count=document.getElementById("notification-count"), panel=document.getElementById("notification-panel"), list=document.getElementById("notification-list"), mark=document.getElementById("mark-notifications-read");
let unsubscribe=null;
function render(items){ if(!list)return; list.innerHTML=""; if(!items.length){list.innerHTML='<p class="notification-empty">No notifications yet.</p>';return;} items.slice(0,30).forEach(item=>{const row=document.createElement("button");row.type="button";row.className=`notification-item ${item.read?"":"unread"}`;const when=item.createdAt?.toDate?item.createdAt.toDate().toLocaleString():"";row.innerHTML=`<strong>${escapeHtml(item.title||"Notification")}</strong><span>${escapeHtml(item.message||"")}</span><small>${escapeHtml(when)}</small>`;row.addEventListener("click",async()=>{if(!item.read)await updateDoc(doc(db,"notifications",item.id),{read:true});if(item.conversationId)window.location.href=`messages.html?conversation=${item.conversationId}`;else if(item.listingId)window.location.href=`product.html?id=${item.listingId}`;});list.appendChild(row);}); }
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
bell?.addEventListener("click",e=>{e.stopPropagation();panel?.classList.toggle("hidden");}); document.addEventListener("click",e=>{if(panel&&!panel.contains(e.target)&&e.target!==bell)panel.classList.add("hidden");});
mark?.addEventListener("click",async()=>{if(!auth.currentUser||!window.__pzNotifications)return;await Promise.all(window.__pzNotifications.filter(x=>!x.read).map(x=>updateDoc(doc(db,"notifications",x.id),{read:true})));});
onAuthStateChanged(auth,user=>{if(unsubscribe){unsubscribe();unsubscribe=null;} if(!user){count?.classList.add("hidden");render([]);return;} const q=query(collection(db,"notifications"),where("userId","==",user.uid)); unsubscribe=onSnapshot(q,snap=>{const items=snap.docs.map(d=>({id:d.id,...d.data()}) );window.__pzNotifications=items;items.sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)); const unread=items.filter(x=>!x.read).length;if(count){count.textContent=unread>99?"99+":String(unread);count.classList.toggle("hidden",unread===0);}render(items);},err=>console.error("Notification error",err));});
