import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged, updateProfile } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { collection, deleteDoc, doc, getDocs, getFirestore, query, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const config={apiKey:"AIzaSyD5tdmon-6R_IABZyUo8QEfSKlTBrmLTo",authDomain:"markethub-prototype.firebaseapp.com",projectId:"markethub-prototype",storageBucket:"markethub-prototype.firebasestorage.app",messagingSenderId:"350124318634",appId:"1:350124318634:web:cb4401e9f84edcdd5995d3"};
const app=getApps().length?getApp():initializeApp(config);const auth=getAuth(app);const db=getFirestore(app);
const signedOut=document.getElementById("profile-signed-out"), page=document.getElementById("profile-page");
const email=document.getElementById("profile-page-email"), member=document.getElementById("profile-page-member"), display=document.getElementById("profile-display-name"), save=document.getElementById("save-profile"), status=document.getElementById("profile-save-status");
const avatar=document.getElementById("profile-page-avatar-image"), placeholder=document.getElementById("profile-page-avatar-placeholder"), photo=document.getElementById("profile-page-photo");
const myListingsEl=document.getElementById("profile-my-listings"), myListingsEmpty=document.getElementById("profile-my-listings-empty"), recentEl=document.getElementById("profile-recent-listings"), recentEmpty=document.getElementById("profile-recent-empty"), savedEl=document.getElementById("profile-saved-searches"), savedEmpty=document.getElementById("profile-saved-searches-empty");
function showPhoto(url){if(url){avatar.src=url;avatar.classList.remove("hidden");placeholder.classList.add("hidden");}else{avatar.classList.add("hidden");placeholder.classList.remove("hidden");}}
function imageFor(x){return x.image||(Array.isArray(x.images)?x.images[0]:"")||"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80";}
function card(x){const a=document.createElement("a");a.className="listing-card profile-listing-card";a.href=`product.html?id=${encodeURIComponent(x.id)}`;a.innerHTML=`<span class="profile-card-arrow">↗</span><img class="listing-image" src="${imageFor(x)}" alt=""><div class="listing-content"><span class="listing-category">${x.category||"Other"}</span><h3 class="listing-title"><span class="listing-title-link">${String(x.title||"Untitled listing").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</span></h3><p class="listing-price">Le ${Number(x.price||0).toLocaleString()}</p><div class="listing-meta"><span>📍 ${x.location||"Freetown"}</span><span>👁 ${Number(x.views||0)}</span></div></div>`;return a;}
function renderCards(target,empty,items){target.innerHTML="";items.forEach(x=>target.appendChild(card(x)));empty.classList.toggle("hidden",items.length>0);}
function renderSavedSearches(items){savedEl.innerHTML="";items.forEach(x=>{const item=document.createElement("article");item.className="saved-search-item";const bits=[];if(x.query)bits.push(`“${x.query}”`);if(x.category&&x.category!=="All")bits.push(x.category);if(x.location)bits.push(x.location);if(x.minPrice)bits.push(`Min Le ${Number(x.minPrice).toLocaleString()}`);if(x.maxPrice)bits.push(`Max Le ${Number(x.maxPrice).toLocaleString()}`);item.innerHTML=`<div><strong>${bits.join(" · ")||"Saved marketplace search"}</strong><small>Saved search</small></div><button type="button" aria-label="Delete saved search">×</button>`;item.querySelector("button").onclick=async()=>{try{await deleteDoc(doc(db,"users",auth.currentUser.uid,"savedSearches",x.id));item.remove();if(!savedEl.children.length)savedEmpty.classList.remove("hidden");}catch(e){console.error(e);alert("Could not delete this saved search.");}};savedEl.appendChild(item);});savedEmpty.classList.toggle("hidden",items.length>0);}
async function load(user){signedOut.classList.add("hidden");page.classList.remove("hidden");email.textContent=user.displayName||user.email||"My Profile";display.value=user.displayName||"";member.textContent=`Member since ${user.metadata.creationTime?new Date(user.metadata.creationTime).toLocaleDateString():"—"}`;showPhoto(user.photoURL);
 const [listings,favs,chats,saved]=await Promise.all([getDocs(query(collection(db,"listings"),where("ownerId","==",user.uid))),getDocs(collection(db,"users",user.uid,"favorites")),getDocs(query(collection(db,"conversations"),where("participants","array-contains",user.uid))),getDocs(collection(db,"users",user.uid,"savedSearches"))]);
 const listingItems=listings.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));
 document.getElementById("profile-stat-listings").textContent=listings.size;document.getElementById("profile-stat-favourites").textContent=favs.size;document.getElementById("profile-stat-messages").textContent=chats.size;
 renderCards(myListingsEl,myListingsEmpty,listingItems.slice(0,10));
 const recentIds=JSON.parse(localStorage.getItem("pz-recently-viewed")||"[]"); const byId=new Map();
 if(recentIds.length){const all=await getDocs(collection(db,"listings"));all.docs.forEach(d=>byId.set(d.id,{id:d.id,...d.data()}));}
 renderCards(recentEl,recentEmpty,recentIds.map(id=>byId.get(id)).filter(Boolean).slice(0,10));
 renderSavedSearches(saved.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)));
}
onAuthStateChanged(auth,user=>{if(user)load(user).catch(e=>console.error(e));else{page.classList.add("hidden");signedOut.classList.remove("hidden");}});
save.addEventListener("click",async()=>{const user=auth.currentUser;if(!user)return;save.disabled=true;try{await updateProfile(user,{displayName:display.value.trim()});email.textContent=display.value.trim()||user.email||"My Profile";status.textContent="Profile saved.";status.classList.remove("hidden");}catch(e){console.error(e);status.textContent="Could not save profile.";status.classList.remove("hidden");}finally{save.disabled=false;}});
photo.addEventListener("change",async()=>{const file=photo.files?.[0],user=auth.currentUser;if(!file||!user)return;if(file.size>8*1024*1024){alert("Profile photo must be 8 MB or smaller.");return;}const fd=new FormData();fd.append("file",file);fd.append("upload_preset","marketplace_unsigned");try{status.textContent="Uploading photo...";status.classList.remove("hidden");const res=await fetch("https://api.cloudinary.com/v1_1/sgagbjny/image/upload",{method:"POST",body:fd});if(!res.ok)throw new Error("Upload failed");const data=await res.json();await updateProfile(user,{photoURL:data.secure_url});showPhoto(data.secure_url);status.textContent="Profile photo updated.";}catch(e){console.error(e);status.textContent="Photo upload failed.";}});
